# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main", "github_actions" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: true

    - uses: actions/cache@v3

    - uses: lukka/get-cmake@latest

    - name: Bootstrap vcpkg
      run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh


    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'vcpkg-release'
        buildPreset: 'release'

    - name: Run latest
      run: ctest --output-on-failure --test-dir build/release

